spring:
  application:
    name: intelliview
  datasource:
    url: jdbc:postgresql://localhost:5432/intelliview
    username: root
    password: 14357
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC